env:
  browser: false
  es2021: true
root: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended-type-checked'
  - 'plugin:@typescript-eslint/stylistic-type-checked'
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
#ignorePatterns: #- dist/
overrides:
  - files:
      - "**/*.ts"
    rules:
      indent:
        - error
        - tab
      linebreak-style:
        - error
        - unix
      quotes:
        - error
        - single
      semi:
        - error
        - never
      max-len:
        - error
        - code: 100
          ignoreComments: true
          ignoreUrls: true
          ignoreStrings: true
          ignoreTemplateLiterals: true
      eol-last:
        - error
        - always
