name: "yargi-machine"
description: "A cli tool to bring justice to your codebase and judge you."

inputs:
  pull-request-command:
    description: "Pass command for -t <title>, -b <branch-name>, -p <file>"
    required: false
  pull-request-value:
    description: "Pass value for -t to <title>, -b to <branch-name>, -p to <file>"
    required: false

outputs:
  result:
    description: "command output"

runs:
  using: "docker"
  image: "Dockerfile.action"
  args:
    - pull-request ${{ inputs.pull-request-command }} "${{ inputs.pull-request-value }}"

branding:
  icon: "triangle"
  color: "blue"
