name: Trigger Releases

on:
  pull_request:
    types:
      - "closed"

permissions:
  contents: read

jobs:
  to-pre-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'beta')
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Pre-release"

  to-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Release"

  from-release:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release-') &&
      !contains(github.event.pull_request.head.ref, '-rc.')
    permissions:
      contents: write # to be able to publish a GitHub release
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP }}

      - name: Create pull request
        id: cpr-pre
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: chore/sync
          delete-branch: false
          title: "chore: sync branches"
          commit-message: "chore: sync branches"
          draft: false
          base: master
          add-paths: |
            docs/CHANGELOG.md
            package.json
            package-lock.json
          labels: |
            report
            automated pr
            sync
          body: |
            Automated Update

            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
