name: Trigger Releases

on:
  pull_request:
    types:
      - "closed"

permissions:
  contents: read

jobs:
  to-pre-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'beta')
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Pre-release"

  to-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Release"

  from-release:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release-')
    permissions:
      contents: write # to be able to publish a GitHub release
      actions: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: install convco
        run: cargo install convco

      - name: get current version
        id: release
        run: |
          echo "VERSION=v$(convco version)" >> $GITHUB_ENV

      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        if: |
          !contains(github.event.pull_request.head.ref, '-rc.')
        with:
          workflow: cd.yaml
          inputs: '{ "tag": "${{ env.VERSION }}" }'

      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        if: |
          contains(github.event.pull_request.head.ref, '-rc.')
        with:
          workflow: cd.yaml
          inputs: '{ "tag": "${{ env.VERSION }}", "staging": true }'
