name: CD

on:
  workflow_dispatch:
    inputs:
      staging:
        description: "Identify as whether staging or not"
        required: false
        default: false
        type: boolean
      tag:
        description: "The version tag"
        required: true
        type: string

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  docker-image:
    name: Generate docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      # For mobile project, generate apk or ipa for this step
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}/${{ inputs.tag }}
          cache-from: type=registry,ref=${{ inputs.tag }}
          cache-to: type=inline

      - name: Test the image
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}/${{ inputs.tag }} -V

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}/${{ inputs.tag }}
          cache-from: type=registry,ref=${{ inputs.tag }}
          cache-to: type=inline
      # If it's staging, push to Firebase app distribution
      # Else stores via fastlane (for mobile)
