name: Pre-release

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "The specific commit hash to pre-release"
        required: false
        type: string

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    outputs:
      version: ${{ steps.release.outputs.version }}
      ref: ${{ steps.ref.outputs.ref }}
    env:
      ENV: "prerelease"
    steps:
      - name: Get commit ref
        if: inputs.commit != ''
        run: echo "REF=${{ inputs.commit }}" >> $GITHUB_ENV

      - name: Get base ref
        if: inputs.commit == ''
        run: echo "REF=master" >> $GITHUB_ENV

      - name: Set ref
        id: ref
        run: echo "ref=${{ env.REF }}" >> $GITHUB_OUTPUT

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.REF }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-pre
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-notes:
    name: Generate Release notes
    runs-on: ubuntu-latest
    needs: [ release ]
    permissions:
      contents: write # to be able to publish a GitHub release
      discussions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ needs.release.outputs.version }}
          prerelease: true
          generate_release_notes: false

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff-r
        with:
          config: ./config/cliff-pre.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: ./.CHANGES.md

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ needs.release.outputs.version }}
          body_path: ./.CHANGES.md
          prerelease: true
          generate_release_notes: false

  upload-files:
    name: upload files after release
    runs-on: ubuntu-latest
    needs: [ release ]
    permissions:
      contents: write # to be able to publish a GitHub release
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP }}

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Update package version
        run: npm version --no-git-tag-version "${{ needs.release.outputs.version }}" --allow-same-version

      - name: Create pull request
        id: cpr-pre
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: release-v${{ needs.release.outputs.version }}
          delete-branch: false
          title: "chore: release artifacts"
          commit-message: "chore(prerelease): update docs & version"
          draft: false
          base: master
          add-paths: |
            package.json
            package-lock.json
          labels: |
            report
            automated pr
            changelog
            versioning
          body: |
            Automated Update

            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
